Feature/performance enhancement
fivetran/dbt_jira pull request #127
Opened 2024-04-05 04:33 UTC by fivetran-catfritz

## PR Overview
**This PR will address the following Issue/Feature:**

**This PR will result in the following new package version:**

**Please provide the finalized CHANGELOG entry which details the relevant changes included in this PR:**

## PR Checklist
### Basic Validation
Please acknowledge that you have successfully performed the following commands locally:
- [ ] dbt run –full-refresh && dbt test
- [ ] dbt run (if incremental models are present) && dbt test

Before marking this PR as "ready for review" the following have been applied:
- [ ] The appropriate issue has been linked, tagged, and properly assigned
- [ ] All necessary documentation and version upgrades have been applied
- [ ] docs were regenerated (unless this PR does not include any code or yml updates)
- [ ] BuildKite integration tests are passing
- [ ] Detailed validation steps have been provided below

### Detailed Validation
Please share any and all of your validation steps:

### If you had to summarize this PR in an emoji, which would it be?
 
:dancer:

2024-04-05 05:10 UTC, fivetran-catfritz commented on packages.yml
> +    warn-unpinned: false
Update before merge
```suggestion
 - package: fivetran/jira_source
   version: [">=0.7.0", "<0.8.0"]
```

2024-04-08 14:53 UTC, fivetran-catfritz commented
Will regen docs after final approval

2024-04-10 18:50 UTC, fivetran-joemarkiewicz requested changes
@fivetran-catfritz Great work on this PR!! I just have a few comments to address. Overall though this PR is great and passed all my stress tests!! Once you have made the final updates and regen the docs then this should be good to be approved!

2024-04-16 00:27 UTC, fivetran-catfritz reviewed
Thanks @fivetran-joemarkiewicz. Updated and ready for re-review!

2024-04-16 00:27 UTC, fivetran-catfritz commented on models/intermediate/field_history/int_jira__issue_calendar_spine.sql
> +    {% if is_incremental() %}
Yes this is intentional. The first part is not used to find new records, but is used to limit the initial size of the spine using `min(earliest_open_until_date)` but with an adequate range for backfilling before the final `max(date_day)` filter, so no lookback is necessary.

2024-04-16 00:27 UTC, fivetran-catfritz commented on models/intermediate/int_jira__issue_type_parents.sql
> +{{ config(materialized='view') }}
It used to be a table, but needs to be at least a view to use the dbt_utils.star macro in int_jira__issue_users.

2024-04-16 20:26 UTC, fivetran-joemarkiewicz approved these changes
LGTM! Great work on this PR @fivetran-catfritz

2024-04-30 23:37 UTC, merged