Bug/issue enhanced  use latest sprint
fivetran/dbt_jira pull request #76
Opened 2022-11-04 22:51 UTC by fivetran-catfritz

**Are you a current Fivetran customer?** 

**What change(s) does this PR introduce?** 

**Did you update the CHANGELOG?** 

- [ ] Yes

**Does this PR introduce a breaking change?**

- [ ] Yes (please provide breaking change details below.)
- [ ] No  (please provide an explanation as to how the change is non-breaking below.)

**Did you update the dbt_project.yml files with the version upgrade (please leverage standard semantic versioning)? (In both your main project and integration_tests)** 

- [ ] Yes

**Is this PR in response to a previously created Bug or Feature Request**

- [ ] Yes, Issue/Feature [link bug/feature number here]
- [ ] No 

**How did you test the PR changes?** 

 

- [ ] CircleCi  
- [ ] Local (please provide additional testing details below)

**Select which warehouse(s) were used to test the PR**
 

- [ ] BigQuery
- [ ] Redshift
- [ ] Snowflake
- [ ] Postgres
- [ ] Databricks
- [ ] Other (provide details below)

**Provide an emoji that best describes your current mood**
 
:dancer:

**Feedback**

We are so excited you decided to contribute to the Fivetran community dbt package! We continue to work to improve the packages and would greatly appreciate your [feedback](https://www.surveymonkey.com/r/DQ7K7WW) on our existing dbt packages or what you'd like to see next.

2022-11-10 16:00 UTC, fivetran-reneeli commented on CHANGELOG.md
> +- The default schema for the source tables are now built within a schema titled (`<target_schema>` + `_jira_source`) in your destination. The previous default schema was (`<target_schema>` + `_stg_ji
a lil typo!

2022-11-10 16:39 UTC, fivetran-reneeli requested changes
@fivetran-catfritz  looks good, just had some minor edits!

2022-11-10 22:06 UTC, fivetran-catfritz commented on CHANGELOG.md
> +- The default schema for the source tables are now built within a schema titled (`<target_schema>` + `_jira_source`) in your destination. The previous default schema was (`<target_schema>` + `_stg_ji
Fixed!

2022-11-10 23:17 UTC, fivetran-catfritz commented on CHANGELOG.md
> +## 🚨 Breaking Change
Updated!

2022-11-10 23:55 UTC, fivetran-catfritz commented
@fivetran-reneeli I have updated and ready for your review! Thanks!

2022-11-11 04:00 UTC, fivetran-reneeli approved these changes
Looks good!

2022-11-14 15:50 UTC, merged