Bug: Making sure components data is properly joined onto JIRA daily issue field history and downstream models
fivetran/dbt_jira pull request #99
Opened 2023-05-09 15:35 UTC by fivetran-avinash

## PR Overview
**This PR will address the following Issue/Feature:** #83

**This PR will result in the following new package version:** `v0.14.0`

This is a breaking change as a `dbt run --full-refresh` is required to reflect the proper components data for customers. 

**Please detail what change(s) this PR introduces and any additional information that should be known during the review of this PR:**

The main issue customers are facing is components data was being joined in incorrectly because there would be identifiers in `field_option` that would have the same id as a `component`.

So when the join  below is executed within `jira__daily_issue_field_history`, it returns the field option values instead of the component names for the component fields.

<img width="1104" alt="Screenshot 2023-05-10 at 1 29 01 PM" src="https://github.com/fivetran/dbt_jira/assets/108772760/7c716f4d-afad-4ca5-85c3-ea144201f8e2">

This PR addresses this issue by ensuring we join on components separately from the field option model. The customer must be utilizing the components source model and specifying `components` as a field in the `issue_field_history_columns` in the `dbt_project.yml` for generating historical data for `jira__daily_issue_field_history`. If neither of those conditions hold, components is then removed from `jira__daily_issue_field_history` to avoid any improper joins. See lines 113-116 and lines 127-130 for the modifications in this join.

<img width="1133" alt="Screenshot 2023-05-10 at 1 54 33 PM" src="https://github.com/fivetran/dbt_jira/assets/108772760/da1f7bab-37ea-41fb-9eb0-b441e615ca4c">

This conditional is then implemented throughout the model so that there are no issues for customers who choose not to leverage components as well.

## PR Checklist
### Basic Validation
Please acknowledge that you have successfully performed the following commands locally:
- [x] dbt compile
- [x] dbt run –full-refresh
- [x] dbt run
- [x] dbt test
- [x] dbt run –vars (if applicable)

Before marking this PR as "ready for review" the following have been applied:
- [x] The appropriate issue has been linked and tagged
- [x] You are assigned to the corresponding issue and this PR
- [x] BuildKite integration tests are passing

### Detailed Validation
Please acknowledge that the following validation checks have been performed prior to marking this PR as "ready for review":
- [x] You have validated these changes and assure this PR will address the respective Issue/Feature.
- [x] You are reasonably confident these changes will not impact any other components of this package or any dependent packages.
- [x] You have provided details below around the validation steps performed to gain confidence in these changes.
  
  
**Bug replication**. 
  
Look at `field_id` = 10019 for the `field_option` source model:
<img width="928" alt="Screenshot 2023-05-09 at 10 43 40 PM" src="https://github.com/fivetran/dbt_jira/assets/108772760/0fba8214-ddb2-4bfe-8f9b-4f4b2a9b3011">

Then see the `id` = 10019 for the `component` source model:
<img width="969" alt="Screenshot 2023-05-09 at 10 43 36 PM" src="https://github.com/fivetran/dbt_jira/assets/108772760/7e9116c0-dcc1-46e2-abb6-54f3a6c3f0b7">

Thus the component values returned downstream when the intial join occurs incorrectly returns the field_option values rather than the component names for the components field.

<img width="919" alt="Screenshot 2023-05-09 at 10 29 16 PM" src="https://github.com/fivetran/dbt_jira/assets/108772760/e5350cbd-948c-41f9-9bb8-400f877ee236">
So we need to isolate components with its own specific logic.    
   

**PR solution and implementation**   
With the new join described above in the PR description, we ensure that if components exist, and are one of the fields mentioned in the issue field history table, any join from the existing table on the components field joins on the components table instead of field option and grabs the correct component names.

We made sure our seed files had the proper components information to be joined upstream

<img width="556" alt="Screenshot 2023-05-10 at 3 23 46 PM" src="https://github.com/fivetran/dbt_jira/assets/108772760/838448a8-3983-486f-8bb5-ae490161d233">
<img width="727" alt="Screenshot 2023-05-10 at 3 23 42 PM" src="https://github.com/fivetran/dbt_jira/assets/108772760/fabcd356-18a7-477c-bb33-31b668bf87a8">
<img width="1148" alt="Screenshot 2023-05-10 at 3 23 37 PM" src="https://github.com/fivetran/dbt_jira/assets/108772760/d518722e-0d15-4152-91a4-0603bd0f50c9">

As you can see, the new version of the model returns the component value.

<img width="867" alt="Screenshot 2023-05-10 at 12 01 16 AM" src="https://github.com/fivetran/dbt_jira/assets/108772760/2d521e17-68f7-4a3b-877c-4de367cac006">

Looking upstream at models that flow from the daily issue field history like `jira__issue_enhanced`, you can see components is also being properly brought in. 

<img width="1260" alt="Screenshot 2023-05-10 at 12 25 06 AM" src="https://github.com/fivetran/dbt_jira/assets/108772760/e713cb06-b876-4884-b6c2-653607ac4f3c">
We're on the right track!  
  

**What happens if components are not configured or part of field history?**  

Say we remove components from the `issue_field_history_columns`  in our `dbt_project.yml`. That means we should only return `summary` and `story points` if those fields are present in the `issue_field_history`

We added `summary` rows to our seed files to test this (see the above seed files for the intial PR fix.

The resulting `jira__daily_issue_field_history`. was the following after execution.  

<img width="1210" alt="Screenshot 2023-05-10 at 1 10 01 PM" src="https://github.com/fivetran/dbt_jira/assets/108772760/67e9df5e-4bbe-42e6-9a3a-70c7db4c894a">

You can see that components is now removed after being included in the initial run, but the summary field is populated with the appropriate information.

Similar behavior occurs when the variable `jira_using_components` is set to false.   
  
**What happens on an incremental load?**

Because of the potential sizing of the `jira__daily_issue_field_history` model, many customers opt to do incremental loads to only load the most recent set of updated rows. We tested this by modifying the `int_jira__issue_calendar_spine` to filter on a specific date range so only certain components are returned up to a certain day, then running a `dbt run --full-refresh`.

<img width="1043" alt="Screenshot 2023-05-10 at 11 03 05 AM" src="https://github.com/fivetran/dbt_jira/assets/108772760/fbc34f8c-2880-419a-9b39-437e8f442225">

This would then return records for this issue up to '2020-11-14'.
<img width="1271" alt="Screenshot 2023-05-10 at 11 27 32 AM" src="https://github.com/fivetran/dbt_jira/assets/108772760/f796216d-e690-4d0c-a8c4-e7401a5045c1">

We then modified the date range by a day ('2020-11-15'), then executed a `dbt run` to see if the components loaded properly.
![Screenshot 2023-05-10 at 12 36 58 PM](https://github.com/fivetran/dbt_jira/assets/108772760/297a57d3-4d3a-474f-be52-7f28c7c32f38)

![Screenshot 2023-05-10 at 12 32 05 PM](https://github.com/fivetran/dbt_jira/assets/108772760/2c1155a4-74a5-42f6-ae81-98251281291f)

Just to be safe, we then modified the date range filter in the calendar spine by several days (up to '2020-11-21') to see if there was any issue with multiple dates being incrementally loaded, then executed a `dbt run`.

<img width="912" alt="Screenshot 2023-05-10 at 12 50 35 PM" src="https://github.com/fivetran/dbt_jira/assets/108772760/1be879c4-4a0e-4edf-91b6-e5b1fe011d06">

All looks good!

Running the same steps when components are not being utilized achieved similar results to above--a successful load of the `summary` field by day, with components excluded.   
  
**Non-incremental sense check**

Removing the date_day filters on `int_jira__issue_calendar_spine` and running `dbt run --full-refresh` and `dbt run` on `jira__daily_issue_field_history` yields the full table of results with the c [...]

2023-05-16 22:01 UTC, fivetran-joemarkiewicz requested changes
@fivetran-avinash great job on this PR! I really appreciate the thoughtfulness you put into your submission as it was incredibly helpful when reviewing and understanding the different scenarios that we need to cover with this addition. 🏅 

When reviewing this PR I wanted to look up what components are and how customers leverage them. I came across [this forum post](https://community.atlassian.com/t5/Jira-questions/Choosing-multiple-components-when-creating-a-task/qaq-p/1261130) where a Jira user adds up to 50 components to a single issue 🙀! I noticed we only tested the logic when one component is selected. As such, I wanted to do a quick test on our own internal data (issue_id = 10091, and schema `jira_3`) and decided to add multiple components.

I re-ran the model for an incremental load and saw the incremental logic work as intended! It captured the update today and inserted the new records. However, it looks like it inserted the IDs and not the actual name of the components. It seems that since these components are string_agg'd in an earlier model, the [join](https://github.com/fivetran/dbt_jira/blob/0efed28dd936ea282ad6c4a7d28d5c347aed2ca8/models/jira__daily_issue_field_history.sql#L127-L130) in your PR does not work as expected when there are multiple components. 

![image](https://github.com/fivetran/dbt_jira/assets/74217849/77a4bfce-8f0f-45bd-a402-0e3eea44b652)


I did some digging and found [where the string_agg takes place](https://github.com/fivetran/dbt_jira/blob/0efed28dd936ea282ad6c4a7d28d5c347aed2ca8/models/intermediate/field_history/int_jira__agg_multiselect_history.sql#L49). Do you think there is a way we could update the package to account for multiple components? I wonder if adding the component join logic that you have in the `jira__daily_issue_field_hstory` to a cte in the `int_jira__agg_multiselect_history` could do the trick. Open to your thoughts!

2023-05-17 20:31 UTC, fivetran-avinash commented on CHANGELOG.md
> +- Please note, a `dbt run --full-refresh` will be required after upgrading to this version in order to capture the updates.
Noted!

2023-05-17 20:41 UTC, fivetran-avinash commented
@fivetran-joemarkiewicz The above issue has been addressed to bring in component ids if there are multiple values, but hasn't been addressed to change them back into component names. Additionally, I'm seeing this issue recur for other field values, like sprints. See the below screenshot. 
![Screenshot 2023-05-17 at 1 01 53 PM](https://github.com/fivetran/dbt_jira/assets/108772760/54de44e6-13cf-4446-85d1-42cc1df67ff2)

So, we will need to create a new feature request to handle this particular inconsistency. 

For the purposes of this bug though, it does bring in the proper component values for each issue and day (even if in varying name or id form), so this should close out this particular task.

2023-05-17 21:22 UTC, fivetran-joemarkiewicz approved these changes
lgtm

2023-05-17 21:23 UTC, merged